### ISSUE TITLE
Navnegivning av repo

### ISSUE THREAD

**Issue by aflaten** [navikt/sokos-mikrofrontend-template#107]
Bør ikke kreve at navn på repo prefikses med `sokos-okonomiportalen-`

```
#!/bin/bash

default="sokos-mikrofrontend-template"

echo '**** Setup for sokos-mikrofrontend-template ****'
echo
read -p 'Project name (sokos-okonomiportalen-xxxx): ' projectName
echo

grep -rl $default --exclude=setupTemplate.sh | xargs -I@ sed -i '' "s|$default|sokos-okonomiportalen-$projectName|g" @
Footer
© 2023 GitHub, Inc.
Footer navigation
```

**Comment by mudasar187** [comment]
Vi ønsker helst at alle mikrofrontendene skal heter sokos-op-navn. Så i deres tilfelle ønsker vi det blir sokos-op-kontoregister :) Tok det opp med teamet og vi ønsker prefix med sokos-op-navn slik at vi kan vite hva som tilhører hva :)
